### ISSUE TITLE
I have a question and need you help.

### ISSUE THREAD

**Issue by e110110eee** [junedchhipa/stacked-cards#1]
thank you for sharing code .i have a question about stackedCard.js.
` if (swipedir =='left') { activeEl.nextElementSibling.click();  }
   else if(swipedir=="right") {  activeEl.previousElementSibling.click()}`
i think  if (swipedir =='left') {   activeEl.previousElementSibling.click();  }
can u tell me why? thank u ! i'm so sorry about my english.

**Comment by junedchhipa** [comment]
if(swipedir=='left') means user swiped left on mobile, try doing this on mobile.
![image](https://cloud.githubusercontent.com/assets/17950663/23354925/5c1b3060-fcf9-11e6-97f5-8a008073fb5f.png)
So technically, he wants to see the next element. Hence, nextElementSibling.click()
